
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/apps/gateway/main.js
    ports:
      - "8080:3000"
    depends_on:
      - auth
      - event
    env_file:
      - apps/gateway/.env

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/apps/auth/main.js
    ports:
      - "8081:3001"
    depends_on:
      - mongodb
    env_file:
      - apps/auth/.env

  event:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/apps/event/main.js
    ports:
      - "8082:3002"
    depends_on:
      - mongodb
    env_file:
      - apps/event/.env

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
