services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev:auth
    ports:
      - "3001:3001"
    volumes:
      - .:/apps
      - /apps/node_modules
    env_file:
      - apps/auth/.env
    depends_on:
      - mongodb

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev:gateway
    ports:
      - "3000:3000"
    volumes:
      - .:/apps
      - /apps/node_modules
    env_file:
      - apps/gateway/.env
    depends_on:
      - auth
      - event

  event:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev:event
    ports:
      - "3002:3002"
    volumes:
      - .:/apps
      - /apps/node_modules
    env_file:
      - apps/event/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
